name: Docker CI
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.gitignore'
      - 'README.md'
  schedule:
    - cron:  '15 0 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure Docker
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - name: Build 22.04
      run: docker build . --pull --build-arg VERSION=22.04 --tag bshp/ubuntu:latest --progress=plain --no-cache
    - name: Push 22.04
      run: |
        docker tag bshp/ubuntu:latest bshp/ubuntu:22.04
        docker tag bshp/ubuntu:latest bshp/ubuntu:jammy
        docker tag bshp/ubuntu:latest bshp/ubuntu:lts
        docker push bshp/ubuntu:22.04
        docker push bshp/ubuntu:jammy
        docker push bshp/ubuntu:lts
    - name: Build 24.04
      run: docker build . --pull --build-arg VERSION=24.04 --tag bshp/ubuntu:24.04 --progress=plain --no-cache
    - name: Push 24.04
      run: |
        docker tag bshp/ubuntu:24.04 bshp/ubuntu:noble
        docker push bshp/ubuntu:24.04
        docker push bshp/ubuntu:noble
