name: Docker CI
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.gitignore'
      - 'README.md'
  schedule:
    - cron:  '15 0 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure Docker
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - name: Build
      run: docker build . --pull --tag bshp/base:latest --progress=plain
    - name: Push
      run: |
        docker tag bshp/base:latest bshp/base:jammy
        docker push bshp/base:latest
        docker push bshp/base:jammy
