name: Docker CI
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.gitignore'
      - 'README.md'
  schedule:
    - cron:  '15 0 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure Docker
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - name: Build 22.04
      run: docker build . --pull --build-arg VERSION=22.04 --tag bshp/base:latest --progress=plain
    - name: Push 22.04
      run: |
        docker tag bshp/base:latest bshp/base:22.04
        docker tag bshp/base:latest bshp/base:jammy
        docker tag bshp/base:latest bshp/base:lts
        docker push bshp/base:22.04
        docker push bshp/base:jammy
        docker push bshp/base:lts
    - name: Build 24.04
      run: docker build . --pull --build-arg VERSION=24.04 --tag bshp/base:24.04 --progress=plain
    - name: Push 24.04
      run: |
        docker tag bshp/base:24.04 bshp/base:noble
        docker push bshp/base:24.04
        docker push bshp/base:noble
